// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.1
// source: cri/proto/invoker.proto

package cri

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InvocationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Image         string                 `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	Command       []string               `protobuf:"bytes,2,rep,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvocationRequest) Reset() {
	*x = InvocationRequest{}
	mi := &file_cri_proto_invoker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvocationRequest) ProtoMessage() {}

func (x *InvocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cri_proto_invoker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvocationRequest.ProtoReflect.Descriptor instead.
func (*InvocationRequest) Descriptor() ([]byte, []int) {
	return file_cri_proto_invoker_proto_rawDescGZIP(), []int{0}
}

func (x *InvocationRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *InvocationRequest) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

type InvocationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Logs          string                 `protobuf:"bytes,2,opt,name=logs,proto3" json:"logs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvocationResponse) Reset() {
	*x = InvocationResponse{}
	mi := &file_cri_proto_invoker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvocationResponse) ProtoMessage() {}

func (x *InvocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cri_proto_invoker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvocationResponse.ProtoReflect.Descriptor instead.
func (*InvocationResponse) Descriptor() ([]byte, []int) {
	return file_cri_proto_invoker_proto_rawDescGZIP(), []int{1}
}

func (x *InvocationResponse) GetLogs() string {
	if x != nil {
		return x.Logs
	}
	return ""
}

var File_cri_proto_invoker_proto protoreflect.FileDescriptor

const file_cri_proto_invoker_proto_rawDesc = "" +
	"\n" +
	"\x17cri/proto/invoker.proto\x12\x03cri\"C\n" +
	"\x11InvocationRequest\x12\x14\n" +
	"\x05image\x18\x01 \x01(\tR\x05image\x12\x18\n" +
	"\acommand\x18\x02 \x03(\tR\acommand\"(\n" +
	"\x12InvocationResponse\x12\x12\n" +
	"\x04logs\x18\x02 \x01(\tR\x04logs2K\n" +
	"\x0eInvokerService\x129\n" +
	"\x06Invoke\x12\x16.cri.InvocationRequest\x1a\x17.cri.InvocationResponseB\x06Z\x04cri/b\x06proto3"

var (
	file_cri_proto_invoker_proto_rawDescOnce sync.Once
	file_cri_proto_invoker_proto_rawDescData []byte
)

func file_cri_proto_invoker_proto_rawDescGZIP() []byte {
	file_cri_proto_invoker_proto_rawDescOnce.Do(func() {
		file_cri_proto_invoker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cri_proto_invoker_proto_rawDesc), len(file_cri_proto_invoker_proto_rawDesc)))
	})
	return file_cri_proto_invoker_proto_rawDescData
}

var file_cri_proto_invoker_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_cri_proto_invoker_proto_goTypes = []any{
	(*InvocationRequest)(nil),  // 0: cri.InvocationRequest
	(*InvocationResponse)(nil), // 1: cri.InvocationResponse
}
var file_cri_proto_invoker_proto_depIdxs = []int32{
	0, // 0: cri.InvokerService.Invoke:input_type -> cri.InvocationRequest
	1, // 1: cri.InvokerService.Invoke:output_type -> cri.InvocationResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cri_proto_invoker_proto_init() }
func file_cri_proto_invoker_proto_init() {
	if File_cri_proto_invoker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cri_proto_invoker_proto_rawDesc), len(file_cri_proto_invoker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cri_proto_invoker_proto_goTypes,
		DependencyIndexes: file_cri_proto_invoker_proto_depIdxs,
		MessageInfos:      file_cri_proto_invoker_proto_msgTypes,
	}.Build()
	File_cri_proto_invoker_proto = out.File
	file_cri_proto_invoker_proto_goTypes = nil
	file_cri_proto_invoker_proto_depIdxs = nil
}
