// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.33.1
// source: proto/git-server.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// List
type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RepoPath      string                 `protobuf:"bytes,1,opt,name=repo_path,json=repoPath,proto3" json:"repo_path,omitempty"`
	ForPush       bool                   `protobuf:"varint,2,opt,name=for_push,json=forPush,proto3" json:"for_push,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_proto_git_server_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_git_server_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_proto_git_server_proto_rawDescGZIP(), []int{0}
}

func (x *ListRequest) GetRepoPath() string {
	if x != nil {
		return x.RepoPath
	}
	return ""
}

func (x *ListRequest) GetForPush() bool {
	if x != nil {
		return x.ForPush
	}
	return false
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Refs          string                 `protobuf:"bytes,1,opt,name=refs,proto3" json:"refs,omitempty"`
	Err           string                 `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_proto_git_server_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_git_server_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_proto_git_server_proto_rawDescGZIP(), []int{1}
}

func (x *ListResponse) GetRefs() string {
	if x != nil {
		return x.Refs
	}
	return ""
}

func (x *ListResponse) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

// Fetch
type FetchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RepoPath      string                 `protobuf:"bytes,1,opt,name=repo_path,json=repoPath,proto3" json:"repo_path,omitempty"`
	Wants         []string               `protobuf:"bytes,2,rep,name=wants,proto3" json:"wants,omitempty"`
	Haves         []string               `protobuf:"bytes,3,rep,name=haves,proto3" json:"haves,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchRequest) Reset() {
	*x = FetchRequest{}
	mi := &file_proto_git_server_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchRequest) ProtoMessage() {}

func (x *FetchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_git_server_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchRequest.ProtoReflect.Descriptor instead.
func (*FetchRequest) Descriptor() ([]byte, []int) {
	return file_proto_git_server_proto_rawDescGZIP(), []int{2}
}

func (x *FetchRequest) GetRepoPath() string {
	if x != nil {
		return x.RepoPath
	}
	return ""
}

func (x *FetchRequest) GetWants() []string {
	if x != nil {
		return x.Wants
	}
	return nil
}

func (x *FetchRequest) GetHaves() []string {
	if x != nil {
		return x.Haves
	}
	return nil
}

type FetchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PackfileChunk []byte                 `protobuf:"bytes,1,opt,name=packfile_chunk,json=packfileChunk,proto3" json:"packfile_chunk,omitempty"`
	Err           string                 `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchResponse) Reset() {
	*x = FetchResponse{}
	mi := &file_proto_git_server_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchResponse) ProtoMessage() {}

func (x *FetchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_git_server_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchResponse.ProtoReflect.Descriptor instead.
func (*FetchResponse) Descriptor() ([]byte, []int) {
	return file_proto_git_server_proto_rawDescGZIP(), []int{3}
}

func (x *FetchResponse) GetPackfileChunk() []byte {
	if x != nil {
		return x.PackfileChunk
	}
	return nil
}

func (x *FetchResponse) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

// Push
type PushRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*PushRequest_Metadata
	//	*PushRequest_PackfileChunk
	Payload       isPushRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushRequest) Reset() {
	*x = PushRequest{}
	mi := &file_proto_git_server_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushRequest) ProtoMessage() {}

func (x *PushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_git_server_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushRequest.ProtoReflect.Descriptor instead.
func (*PushRequest) Descriptor() ([]byte, []int) {
	return file_proto_git_server_proto_rawDescGZIP(), []int{4}
}

func (x *PushRequest) GetPayload() isPushRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *PushRequest) GetMetadata() *PushMetadata {
	if x != nil {
		if x, ok := x.Payload.(*PushRequest_Metadata); ok {
			return x.Metadata
		}
	}
	return nil
}

func (x *PushRequest) GetPackfileChunk() []byte {
	if x != nil {
		if x, ok := x.Payload.(*PushRequest_PackfileChunk); ok {
			return x.PackfileChunk
		}
	}
	return nil
}

type isPushRequest_Payload interface {
	isPushRequest_Payload()
}

type PushRequest_Metadata struct {
	Metadata *PushMetadata `protobuf:"bytes,1,opt,name=metadata,proto3,oneof"`
}

type PushRequest_PackfileChunk struct {
	PackfileChunk []byte `protobuf:"bytes,2,opt,name=packfile_chunk,json=packfileChunk,proto3,oneof"`
}

func (*PushRequest_Metadata) isPushRequest_Payload() {}

func (*PushRequest_PackfileChunk) isPushRequest_Payload() {}

type PushMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RepoPath      string                 `protobuf:"bytes,1,opt,name=repo_path,json=repoPath,proto3" json:"repo_path,omitempty"`
	RefUpdates    []*RefUpdate           `protobuf:"bytes,2,rep,name=ref_updates,json=refUpdates,proto3" json:"ref_updates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushMetadata) Reset() {
	*x = PushMetadata{}
	mi := &file_proto_git_server_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushMetadata) ProtoMessage() {}

func (x *PushMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_git_server_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushMetadata.ProtoReflect.Descriptor instead.
func (*PushMetadata) Descriptor() ([]byte, []int) {
	return file_proto_git_server_proto_rawDescGZIP(), []int{5}
}

func (x *PushMetadata) GetRepoPath() string {
	if x != nil {
		return x.RepoPath
	}
	return ""
}

func (x *PushMetadata) GetRefUpdates() []*RefUpdate {
	if x != nil {
		return x.RefUpdates
	}
	return nil
}

type RefUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefName       string                 `protobuf:"bytes,1,opt,name=ref_name,json=refName,proto3" json:"ref_name,omitempty"`
	OldHash       string                 `protobuf:"bytes,2,opt,name=old_hash,json=oldHash,proto3" json:"old_hash,omitempty"`
	NewHash       string                 `protobuf:"bytes,3,opt,name=new_hash,json=newHash,proto3" json:"new_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefUpdate) Reset() {
	*x = RefUpdate{}
	mi := &file_proto_git_server_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefUpdate) ProtoMessage() {}

func (x *RefUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_git_server_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefUpdate.ProtoReflect.Descriptor instead.
func (*RefUpdate) Descriptor() ([]byte, []int) {
	return file_proto_git_server_proto_rawDescGZIP(), []int{6}
}

func (x *RefUpdate) GetRefName() string {
	if x != nil {
		return x.RefName
	}
	return ""
}

func (x *RefUpdate) GetOldHash() string {
	if x != nil {
		return x.OldHash
	}
	return ""
}

func (x *RefUpdate) GetNewHash() string {
	if x != nil {
		return x.NewHash
	}
	return ""
}

type PushResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Err           string                 `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushResponse) Reset() {
	*x = PushResponse{}
	mi := &file_proto_git_server_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushResponse) ProtoMessage() {}

func (x *PushResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_git_server_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushResponse.ProtoReflect.Descriptor instead.
func (*PushResponse) Descriptor() ([]byte, []int) {
	return file_proto_git_server_proto_rawDescGZIP(), []int{7}
}

func (x *PushResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PushResponse) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

var File_proto_git_server_proto protoreflect.FileDescriptor

const file_proto_git_server_proto_rawDesc = "" +
	"\n" +
	"\x16proto/git-server.proto\x12\x06git.v1\"E\n" +
	"\vListRequest\x12\x1b\n" +
	"\trepo_path\x18\x01 \x01(\tR\brepoPath\x12\x19\n" +
	"\bfor_push\x18\x02 \x01(\bR\aforPush\"4\n" +
	"\fListResponse\x12\x12\n" +
	"\x04refs\x18\x01 \x01(\tR\x04refs\x12\x10\n" +
	"\x03err\x18\x02 \x01(\tR\x03err\"W\n" +
	"\fFetchRequest\x12\x1b\n" +
	"\trepo_path\x18\x01 \x01(\tR\brepoPath\x12\x14\n" +
	"\x05wants\x18\x02 \x03(\tR\x05wants\x12\x14\n" +
	"\x05haves\x18\x03 \x03(\tR\x05haves\"H\n" +
	"\rFetchResponse\x12%\n" +
	"\x0epackfile_chunk\x18\x01 \x01(\fR\rpackfileChunk\x12\x10\n" +
	"\x03err\x18\x02 \x01(\tR\x03err\"u\n" +
	"\vPushRequest\x122\n" +
	"\bmetadata\x18\x01 \x01(\v2\x14.git.v1.PushMetadataH\x00R\bmetadata\x12'\n" +
	"\x0epackfile_chunk\x18\x02 \x01(\fH\x00R\rpackfileChunkB\t\n" +
	"\apayload\"_\n" +
	"\fPushMetadata\x12\x1b\n" +
	"\trepo_path\x18\x01 \x01(\tR\brepoPath\x122\n" +
	"\vref_updates\x18\x02 \x03(\v2\x11.git.v1.RefUpdateR\n" +
	"refUpdates\"\\\n" +
	"\tRefUpdate\x12\x19\n" +
	"\bref_name\x18\x01 \x01(\tR\arefName\x12\x19\n" +
	"\bold_hash\x18\x02 \x01(\tR\aoldHash\x12\x19\n" +
	"\bnew_hash\x18\x03 \x01(\tR\anewHash\"8\n" +
	"\fPushResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x10\n" +
	"\x03err\x18\x02 \x01(\tR\x03err2\xac\x01\n" +
	"\n" +
	"GitService\x121\n" +
	"\x04List\x12\x13.git.v1.ListRequest\x1a\x14.git.v1.ListResponse\x126\n" +
	"\x05Fetch\x12\x14.git.v1.FetchRequest\x1a\x15.git.v1.FetchResponse0\x01\x123\n" +
	"\x04Push\x12\x13.git.v1.PushRequest\x1a\x14.git.v1.PushResponse(\x01B\bZ\x06git/v1b\x06proto3"

var (
	file_proto_git_server_proto_rawDescOnce sync.Once
	file_proto_git_server_proto_rawDescData []byte
)

func file_proto_git_server_proto_rawDescGZIP() []byte {
	file_proto_git_server_proto_rawDescOnce.Do(func() {
		file_proto_git_server_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_git_server_proto_rawDesc), len(file_proto_git_server_proto_rawDesc)))
	})
	return file_proto_git_server_proto_rawDescData
}

var file_proto_git_server_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_git_server_proto_goTypes = []any{
	(*ListRequest)(nil),   // 0: git.v1.ListRequest
	(*ListResponse)(nil),  // 1: git.v1.ListResponse
	(*FetchRequest)(nil),  // 2: git.v1.FetchRequest
	(*FetchResponse)(nil), // 3: git.v1.FetchResponse
	(*PushRequest)(nil),   // 4: git.v1.PushRequest
	(*PushMetadata)(nil),  // 5: git.v1.PushMetadata
	(*RefUpdate)(nil),     // 6: git.v1.RefUpdate
	(*PushResponse)(nil),  // 7: git.v1.PushResponse
}
var file_proto_git_server_proto_depIdxs = []int32{
	5, // 0: git.v1.PushRequest.metadata:type_name -> git.v1.PushMetadata
	6, // 1: git.v1.PushMetadata.ref_updates:type_name -> git.v1.RefUpdate
	0, // 2: git.v1.GitService.List:input_type -> git.v1.ListRequest
	2, // 3: git.v1.GitService.Fetch:input_type -> git.v1.FetchRequest
	4, // 4: git.v1.GitService.Push:input_type -> git.v1.PushRequest
	1, // 5: git.v1.GitService.List:output_type -> git.v1.ListResponse
	3, // 6: git.v1.GitService.Fetch:output_type -> git.v1.FetchResponse
	7, // 7: git.v1.GitService.Push:output_type -> git.v1.PushResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_git_server_proto_init() }
func file_proto_git_server_proto_init() {
	if File_proto_git_server_proto != nil {
		return
	}
	file_proto_git_server_proto_msgTypes[4].OneofWrappers = []any{
		(*PushRequest_Metadata)(nil),
		(*PushRequest_PackfileChunk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_git_server_proto_rawDesc), len(file_proto_git_server_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_git_server_proto_goTypes,
		DependencyIndexes: file_proto_git_server_proto_depIdxs,
		MessageInfos:      file_proto_git_server_proto_msgTypes,
	}.Build()
	File_proto_git_server_proto = out.File
	file_proto_git_server_proto_goTypes = nil
	file_proto_git_server_proto_depIdxs = nil
}
