// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.3
// 	protoc        v3.12.4
// source: cri/proto/runtime.proto

package cri

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RunCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Image         string                 `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	Command       []string               `protobuf:"bytes,2,rep,name=command,proto3" json:"command,omitempty"`
	Mounts        []*ContainerMount      `protobuf:"bytes,3,rep,name=mounts,proto3" json:"mounts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunCodeRequest) Reset() {
	*x = RunCodeRequest{}
	mi := &file_cri_proto_runtime_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunCodeRequest) ProtoMessage() {}

func (x *RunCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cri_proto_runtime_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunCodeRequest.ProtoReflect.Descriptor instead.
func (*RunCodeRequest) Descriptor() ([]byte, []int) {
	return file_cri_proto_runtime_proto_rawDescGZIP(), []int{0}
}

func (x *RunCodeRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *RunCodeRequest) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *RunCodeRequest) GetMounts() []*ContainerMount {
	if x != nil {
		return x.Mounts
	}
	return nil
}

type ContainerMount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Destination   string                 `protobuf:"bytes,1,opt,name=destination,proto3" json:"destination,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Options       []string               `protobuf:"bytes,3,rep,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerMount) Reset() {
	*x = ContainerMount{}
	mi := &file_cri_proto_runtime_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerMount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerMount) ProtoMessage() {}

func (x *ContainerMount) ProtoReflect() protoreflect.Message {
	mi := &file_cri_proto_runtime_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerMount.ProtoReflect.Descriptor instead.
func (*ContainerMount) Descriptor() ([]byte, []int) {
	return file_cri_proto_runtime_proto_rawDescGZIP(), []int{1}
}

func (x *ContainerMount) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *ContainerMount) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *ContainerMount) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

type RunCodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Logs          string                 `protobuf:"bytes,1,opt,name=logs,proto3" json:"logs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunCodeResponse) Reset() {
	*x = RunCodeResponse{}
	mi := &file_cri_proto_runtime_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunCodeResponse) ProtoMessage() {}

func (x *RunCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cri_proto_runtime_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunCodeResponse.ProtoReflect.Descriptor instead.
func (*RunCodeResponse) Descriptor() ([]byte, []int) {
	return file_cri_proto_runtime_proto_rawDescGZIP(), []int{2}
}

func (x *RunCodeResponse) GetLogs() string {
	if x != nil {
		return x.Logs
	}
	return ""
}

var File_cri_proto_runtime_proto protoreflect.FileDescriptor

var file_cri_proto_runtime_proto_rawDesc = []byte{
	0x0a, 0x17, 0x63, 0x72, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x75, 0x6e, 0x74,
	0x69, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x63, 0x72, 0x69, 0x22, 0x6d,
	0x0a, 0x0e, 0x52, 0x75, 0x6e, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e,
	0x64, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64,
	0x12, 0x2b, 0x0a, 0x06, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x13, 0x2e, 0x63, 0x72, 0x69, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72,
	0x4d, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x06, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x22, 0x64, 0x0a,
	0x0e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x4d, 0x6f, 0x75, 0x6e, 0x74, 0x12,
	0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x22, 0x25, 0x0a, 0x0f, 0x52, 0x75, 0x6e, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x6f, 0x67, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x6f, 0x67, 0x73, 0x32, 0x46, 0x0a, 0x0e, 0x52, 0x75,
	0x6e, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x34, 0x0a, 0x07,
	0x52, 0x75, 0x6e, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x13, 0x2e, 0x63, 0x72, 0x69, 0x2e, 0x52, 0x75,
	0x6e, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x63,
	0x72, 0x69, 0x2e, 0x52, 0x75, 0x6e, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x42, 0x06, 0x5a, 0x04, 0x63, 0x72, 0x69, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_cri_proto_runtime_proto_rawDescOnce sync.Once
	file_cri_proto_runtime_proto_rawDescData = file_cri_proto_runtime_proto_rawDesc
)

func file_cri_proto_runtime_proto_rawDescGZIP() []byte {
	file_cri_proto_runtime_proto_rawDescOnce.Do(func() {
		file_cri_proto_runtime_proto_rawDescData = protoimpl.X.CompressGZIP(file_cri_proto_runtime_proto_rawDescData)
	})
	return file_cri_proto_runtime_proto_rawDescData
}

var file_cri_proto_runtime_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_cri_proto_runtime_proto_goTypes = []any{
	(*RunCodeRequest)(nil),  // 0: cri.RunCodeRequest
	(*ContainerMount)(nil),  // 1: cri.ContainerMount
	(*RunCodeResponse)(nil), // 2: cri.RunCodeResponse
}
var file_cri_proto_runtime_proto_depIdxs = []int32{
	1, // 0: cri.RunCodeRequest.mounts:type_name -> cri.ContainerMount
	0, // 1: cri.RuntimeService.RunCode:input_type -> cri.RunCodeRequest
	2, // 2: cri.RuntimeService.RunCode:output_type -> cri.RunCodeResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_cri_proto_runtime_proto_init() }
func file_cri_proto_runtime_proto_init() {
	if File_cri_proto_runtime_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cri_proto_runtime_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cri_proto_runtime_proto_goTypes,
		DependencyIndexes: file_cri_proto_runtime_proto_depIdxs,
		MessageInfos:      file_cri_proto_runtime_proto_msgTypes,
	}.Build()
	File_cri_proto_runtime_proto = out.File
	file_cri_proto_runtime_proto_rawDesc = nil
	file_cri_proto_runtime_proto_goTypes = nil
	file_cri_proto_runtime_proto_depIdxs = nil
}
