// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: invoker.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InvokerService_Invoke_FullMethodName = "/cri.v1.InvokerService/Invoke"
)

// InvokerServiceClient is the client API for InvokerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InvokerServiceClient interface {
	Invoke(ctx context.Context, in *InvocationRequest, opts ...grpc.CallOption) (*InvocationResponse, error)
}

type invokerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInvokerServiceClient(cc grpc.ClientConnInterface) InvokerServiceClient {
	return &invokerServiceClient{cc}
}

func (c *invokerServiceClient) Invoke(ctx context.Context, in *InvocationRequest, opts ...grpc.CallOption) (*InvocationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InvocationResponse)
	err := c.cc.Invoke(ctx, InvokerService_Invoke_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InvokerServiceServer is the server API for InvokerService service.
// All implementations must embed UnimplementedInvokerServiceServer
// for forward compatibility.
type InvokerServiceServer interface {
	Invoke(context.Context, *InvocationRequest) (*InvocationResponse, error)
	mustEmbedUnimplementedInvokerServiceServer()
}

// UnimplementedInvokerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInvokerServiceServer struct{}

func (UnimplementedInvokerServiceServer) Invoke(context.Context, *InvocationRequest) (*InvocationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Invoke not implemented")
}
func (UnimplementedInvokerServiceServer) mustEmbedUnimplementedInvokerServiceServer() {}
func (UnimplementedInvokerServiceServer) testEmbeddedByValue()                        {}

// UnsafeInvokerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InvokerServiceServer will
// result in compilation errors.
type UnsafeInvokerServiceServer interface {
	mustEmbedUnimplementedInvokerServiceServer()
}

func RegisterInvokerServiceServer(s grpc.ServiceRegistrar, srv InvokerServiceServer) {
	// If the following call pancis, it indicates UnimplementedInvokerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InvokerService_ServiceDesc, srv)
}

func _InvokerService_Invoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InvocationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InvokerServiceServer).Invoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InvokerService_Invoke_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InvokerServiceServer).Invoke(ctx, req.(*InvocationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InvokerService_ServiceDesc is the grpc.ServiceDesc for InvokerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InvokerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cri.v1.InvokerService",
	HandlerType: (*InvokerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Invoke",
			Handler:    _InvokerService_Invoke_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "invoker.proto",
}
